all: Eus Dut Est

Eus:
	gf -make --src -gfo-dir /tmp grammars/TestLangEus.gf

Est:
	gf -make --src -gfo-dir /tmp grammars/TestLangEst.gf
	
Eng:
	gf -make --src -gfo-dir /tmp grammars/TestLangEng.gf

Dut:
	gf -make --src -gfo-dir /tmp grammars/TestLangDut.gf